export const catalogoProdutos = [
    {
        codigoProduto: 1,
        nomeProduto:"Base e Corretivo Matte - Bege Claro",
        preco: "R$69,90",
        parcelamento: "R$23,30",
        imagemProduto:"produtos/maquiagem/prod4/1.png",
        descricaoProduto:"Bege Claro 2 - 25g",
        categoria:"Maquiagem",
        mostrarNaHome: true,
        mostrarNovidades: false,
        descricaoadd:" A Base e Corretivo Matte - Bege Claro é um produto inovador que combina os benefícios de uma base e de um corretivo em um único item, proporcionando uma cobertura impecável e um acabamento matte de longa duração. Desenvolvida para atender às necessidades da pele, esta fórmula multifuncional é especialmente formulada para proporcionar um visual natural, uniforme e radiante."
    },
    {
        codigoProduto: 2,
        nomeProduto:"Base e Corretivo Matte - Amêndoa",
        preco: "R$69,90",
        parcelamento: "R$23,30",
        imagemProduto:"produtos/maquiagem/prod5/Frasco-Transparente-Fosco-Base-Corretivo-Alta-Cobertura-Contorno-Iluminacao-Velvet-Skin-Bege-Medio.png",
        descricaoProduto:"Amêndoa - 25g",
        categoria:"Maquiagem",
        mostrarNaHome: true,
        mostrarNovidades: false,
        descricaoadd:"A Base e Corretivo Matte - Amêndoa é um produto revolucionário que combina as propriedades de uma base e de um corretivo em um único produto, oferecendo uma cobertura excepcional e um acabamento matte duradouro. Projetada para atender às demandas variadas da pele, esta fórmula inovadora proporciona uma aparência natural e uniforme, enquanto cuida da sua pele."
    },
    {
        codigoProduto: 3,
        nomeProduto:"Base e Corretivo Matte - Chocolate",
        preco: "R$69,90",
        parcelamento: "R$23,30",
        imagemProduto:"produtos/maquiagem/prod6/1.png",
        descricaoProduto:"Chocolate - 25g",
        categoria:"Maquiagem",
        mostrarNaHome: true,
        mostrarNovidades: false,
        descricaoadd:"A Base e Corretivo Matte - Chocolate é uma inovação na categoria de maquiagem, combinando as propriedades de uma base e de um corretivo em um único produto. Desenvolvida para proporcionar uma cobertura excepcional e um acabamento matte duradouro, esta fórmula versátil é perfeita para realçar a beleza natural da pele."
    },
    {
        codigoProduto: 4,
        nomeProduto:"Base e Corretivo Matte - Cacau",
        preco: "R$69,90",
        parcelamento: "R$23,30",
        imagemProduto:"produtos/maquiagem/prod7/1.png",
        descricaoProduto:"Cacau 2 - 25g",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"A Base e Corretivo Matte - Cacau é um produto inovador que une as propriedades fundamentais de uma base e de um corretivo, proporcionando uma cobertura impecável e um acabamento matte duradouro. Desenvolvida para atender às diversas tonalidades de pele, esta fórmula versátil oferece um visual natural e radiante, ao mesmo tempo que cuida da sua pele."
    },
    {
        codigoProduto: 5,
        nomeProduto:"Blush Extra Dimension MAC - Rosa",
        preco: "R$259,90",
        parcelamento:"R$86,60",
        imagemProduto:"produtos/maquiagem/prod8/1.avif",
        descricaoProduto:"Rosa amarelado médio - 4g",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"O Blush Extra Dimension MAC - Rosa é uma expressão da sofisticação e qualidade que a MAC Cosmetics é conhecida por proporcionar em seus produtos. Este blush icônico oferece uma tonalidade rosa vibrante e uma textura extraordinária para realçar e esculpir as maçãs do rosto, proporcionando um brilho dimensional sutil e radiante."
    },
    {
        codigoProduto: 6,
        nomeProduto:"Blush Extra Dimension MAC - Champanhe",
        preco: "R$259,90",
        parcelamento:"R$86,60",
        imagemProduto:"produtos/maquiagem/prod9/1.avif",
        descricaoProduto:"Champanhe rosado claro - 4g",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"O Blush Extra Dimension MAC - Champanhe é um tesouro na paleta de produtos de maquiagem da MAC Cosmetics, oferecendo uma tonalidade suave de champanhe que ilumina e esculpe as maçãs do rosto. Com uma fórmula inovadora e uma textura luxuosa, este blush proporciona um brilho dimensional e um toque de elegância a qualquer look."
    },
    {
        codigoProduto: 7,
        nomeProduto:"Sombra Para Olhos Dazzleshadow MAC - Bege",
        preco: "R$149,00",
        parcelamento: "R$49,60",
        imagemProduto:"produtos/maquiagem/prod2/1.avif",
        descricaoProduto:"Bege pêssego com cintilante rosa",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"A Sombra Para Olhos Dazzleshadow MAC - Bege é uma obra-prima de maquiagem que combina pigmentação rica, brilho deslumbrante e uma textura suave para criar looks deslumbrantes e expressivos. Esta sombra em tom de bege oferece versatilidade e elegância, sendo um complemento perfeito para qualquer estilo de maquiagem."
    },
    {
        codigoProduto: 8,
        nomeProduto:"Sombra Para Olhos Dazzleshadow MAC - Cinza",
        preco: "R$149,00",
        parcelamento: "R$49,60",
        imagemProduto:"produtos/maquiagem/prod10/1.avif",
        descricaoProduto:"Cinza-claro com cintilante prateado",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"A Sombra Para Olhos Dazzleshadow MAC - Cinza é uma expressão de elegância e modernidade, combinando a riqueza do tom cinza com a deslumbrante fórmula Dazzleshadow da MAC. Essa sombra oferece um brilho sutil e sofisticado, ideal para criar looks versáteis e impactantes.",
    },
    {
        codigoProduto: 9,
        nomeProduto:"Batom Líquido MAC Locked Kiss INK",
        preco: "R$219,00",
        parcelamento: "R$73.00",
        imagemProduto:"produtos/maquiagem/prod1/1.avif",
        descricaoProduto:"Matte Até 24 horas - 4ml",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"O Batom Líquido MAC Locked Kiss INK é uma afirmação ousada de estilo e personalidade. Com uma fórmula inovadora e uma tonalidade única, este batom líquido oferece cor intensa, acabamento matte e durabilidade excepcional, tornando-se um item essencial para quem busca expressar sua individualidade com elegância."
    },
    {
        codigoProduto: 10,
        nomeProduto:"Batom Líquido MAC Powder Kiss",
        preco: "R$219,00",
        parcelamento: "R$73.00",
        imagemProduto:"produtos/maquiagem/prod11/1.avif",
        descricaoProduto:"Rosa fluorescente brilhante - 5ml",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"O Batom Líquido MAC Powder Kiss é uma revolução na experiência do batom, combinando a suavidade do pó com a intensidade do pigmento líquido. Essa fórmula inovadora oferece uma sensação leve e aveludada, proporcionando lábios matificados com uma cor rica e duradoura."
    },
    {
        codigoProduto: 11,
        nomeProduto:"Batom Líquido Retro Matte MAC",
        preco: "R$169,00",
        parcelamento: "R$56,30",
        imagemProduto:"produtos/maquiagem/prod12/1.avif",
        descricaoProduto:"Vermelho profundo - 5ml",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"O Batom Líquido Retro Matte MAC é uma fusão perfeita entre a elegância retrô e a modernidade, proporcionando lábios intensamente pigmentados com um acabamento matte clássico. Essa fórmula líquida combina cor vibrante, durabilidade excepcional e uma sensação leve para uma experiência de maquiagem memorável."
    },
    {
        codigoProduto: 12,
        nomeProduto:"Batom Liquido Love Me MAC",
        preco: "R$179,00",
        parcelamento: "R$59,60",
        imagemProduto:"produtos/maquiagem/prod13/1.avif",
        descricaoProduto:"Nude Acinzentado",
        categoria:"Maquiagem",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"O Batom Líquido Love Me MAC é um convite ao romance e à autoexpressão, oferecendo uma experiência de batom líquido única. Com uma fórmula inovadora, cores apaixonantes e uma textura suave, este batom proporciona lábios irresistíveis, expressando o amor próprio com cada aplicação."
    },
    {
        codigoProduto: 13,
        nomeProduto:"La Roche Posey - Protetor Solar",
        preco: "R$80,95",
        parcelamento: "R$26,98",
        imagemProduto:"produtos/dermocosmeticos/prod1/1.webp",
        descricaoProduto:"Protetor Solar Anthelios Airlicium + FPS80 - 40g",
        categoria:"Dermocosméticos",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"O protetor solar da La Roche-Posay é um produto dedicado à proteção eficaz contra os raios solares, garantindo cuidado e segurança para a sua pele. Com uma abordagem focada na saúde da pele, este protetor solar oferece uma série de benefícios para garantir que sua pele esteja protegida dos danos causados pela exposição ao sol."
    },
    {
        codigoProduto: 14,
        nomeProduto:"CeraVe",
        preco: "R$95,90",
        parcelamento: "R$31,96",
        imagemProduto:"produtos/dermocosmeticos/prod2/1.webp",
        descricaoProduto:"Loção Corporal Hidratante - 473ml",
        categoria:"Dermocosméticos",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"O CeraVe Hidratante é um produto projetado para proporcionar uma hidratação intensa e duradoura para a pele. Desenvolvido com a expertise dos dermatologistas, a fórmula única do CeraVe incorpora ingredientes essenciais para manter a barreira cutânea saudável e reter a umidade natural da pele."
    },
    {
        codigoProduto: 15,
        nomeProduto:"La Roche Posay - Sérum",
        preco: "R$180,99",
        parcelamento:"R$36,33",
        imagemProduto:"produtos/dermocosmeticos/prod3/1.webp",
        descricaoProduto:"Sérum Antirrugas - Retinol B3 - 15ml",
        categoria:"Dermocosméticos",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"A La Roche-Posay oferece uma variedade de séruns para atender às necessidades específicas da pele. Cada sérum é formulado com ingredientes cuidadosamente selecionados para proporcionar benefícios específicos, como hidratação, suavização de rugas, clareamento da pele ou redução da vermelhidão."
    },
    {
        codigoProduto: 16,
        nomeProduto:"Sérum Facial Eucerin Anti-Pigment",
        preco: "R$245,90",
        parcelamento: "R$81,96",
        imagemProduto:"produtos/dermocosmeticos/prod4/1.webp",
        descricaoProduto:"Dual Sérum - 30ml",
        categoria:"Dermocosméticos",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"O Sérum Facial Eucerin Anti-Pigment é um produto desenvolvido pela marca Eucerin para abordar as preocupações relacionadas à hiperpigmentação da pele. Com uma fórmula especializada, este sérum visa atenuar manchas escuras, descolorações e irregularidades no tom da pele, proporcionando um aspecto mais uniforme e luminoso."
    },
    {
        codigoProduto: 17,
        nomeProduto:"Aurien Rubra",
        preco: "R$125,99",
        parcelamento:"R$41,96",
        imagemProduto:"produtos/perfumaria/prod1/1.webp",
        descricaoProduto:"Deo colônia - 100ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"A Colônia Desodorante Aurien Rubra buscou inspiração na alta joalheria internacional para traduzir a feminilidade do ouro rosado nesta fragrância incomparável. Uma beleza única que capta a nobreza do ouro, o brilho da prata e o calor do cobre em uma mistura simplesmente deslumbrante. O lado mais feminino do ouro rosado, fascinante e encantador ao alcance das suas mãos. Uma fragrância floral que carrega todo o poder das pétalas de magnólia."
    },
    {
        codigoProduto: 18,
        nomeProduto:"Coffee Woman Seduction",
        preco: "R$143,90",
        parcelamento: "R$47,66",
        imagemProduto:"produtos/perfumaria/prod2/1.2.webp",
        descricaoProduto:"Desodorante Colônia - 100ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"Coffee Woman Seduction é uma fragrância que faz parte da linha Coffee, conhecida por suas composições que exploram o aroma envolvente e estimulante do café. Este perfume é especialmente projetado para mulheres que buscam uma experiência olfativa cativante e sedutora."
    },
    {
        codigoProduto: 19,
        nomeProduto:"Glamour Just Shine",
        preco: "R$154.90",
        parcelamento: "R$51,33",
        imagemProduto:"produtos/perfumaria/prod3/1.webp",
        descricaoProduto:"Desodorante Colônia  - 100ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"Glamour Just Shine é uma fragrância que sugere brilho, radiância e uma aura de glamour. Este perfume é projetado para mulheres que buscam uma experiência olfativa que capture a luminosidade e a sofisticação, evocando um toque de brilho em sua jornada diária."
    },
    {
        codigoProduto: 20,
        nomeProduto:"Boticollection Dreams",
        preco: "R$169.90",
        parcelamento: "R$56,63",
        imagemProduto:"produtos/perfumaria/prod4/1.webp",
        descricaoProduto:"Desodorante Colônia - 75ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"Boticollection Dreams é uma fragrância da linha de perfumes Boticollection, que é conhecida por oferecer uma variedade de fragrâncias com diferentes temáticas olfativas. Este perfume em particular, Dreams, sugere uma experiência sensorial que evoca sonhos, fantasias e uma jornada olfativa única."
    },
    {
        codigoProduto: 21,
        nomeProduto:"Coffee Woman Duo",
        preco: "R$99,99",
        parcelamento: "R$33,33",
        imagemProduto:"produtos/perfumaria/prod5/1.2.webp",
        descricaoProduto:"Desodorante Colônia  - 100ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"Coffee Woman Duo é um Amadeirado Gourmand que prova que os opostos se atraem. Mistura a delicadeza e cremosidade com o contraste do amargor do café."
    },
    {
        codigoProduto: 22,
        nomeProduto:"Lancôme la vie est belle soleil cristal",
        preco: "R$569,90",
        parcelamento:"R$189,96",
        imagemProduto:"produtos/perfumaria/prod6/1.webp",
        descricaoProduto:"Eau de parfum - 100ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"Lancôme La Vie Est Belle Soleil Cristal é uma variação da icônica fragrância La Vie Est Belle da Lancôme, que é conhecida por suas notas florais e frutadas, bem como por seu frasco distintivo. O Soleil Cristal é uma interpretação que adiciona uma dimensão solar e luminosa à experiência olfativa original."
    },
    {
        codigoProduto: 23,
        nomeProduto:"Good Girl Blush Carolina Herrera",
        preco: "R$719,90",
        parcelamento: "R$239,96",
        imagemProduto:"produtos/perfumaria/prod7/1.webp",
        descricaoProduto:"Eau de Parfum - 80ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: false,
        descricaoadd:"Good Girl Blush é uma variação da fragrância icônica Good Girl da Carolina Herrera. Conhecida por seu frasco em formato de salto alto e por suas notas contrastantes, a Good Girl Blush provavelmente oferece uma interpretação única e cativante da fragrância original, adicionando novos elementos olfativos e visuais."
    },
    {
        codigoProduto: 24,
        nomeProduto:"Dior J adore Parfum",
        preco: "R$479,99",
        parcelamento: "R$159,99",
        imagemProduto:"produtos/perfumaria/prod8/1.webp",
        descricaoProduto:"Eau de Parfum - 30ml",
        categoria:"Perfumes",
        mostrarNaHome: false,
        mostrarNovidades: true,
        descricaoadd:"Dior J'adore é uma linha de fragrâncias da casa de moda Dior, conhecida por suas composições elegantes e femininas. O Dior J'adore Parfum é uma concentração mais intensa da fragrância, proporcionando uma experiência olfativa ainda mais rica e duradoura em comparação com as versões mais leves, como a Eau de Parfum ou a Eau de Toilette."
    },
    
]
